version: "3.8"
services:
  nodejs_endgames:
    container_name: "chessEndgamesServer"
    image: "nodejs-chess_end_games_server:3"
    volumes:
      - "../:/app"
    build:
      context: ./nodejs
    restart: always
    ports:
      - "4000:4000"
